/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diepafiskaki;

/**
 *
 * @author harisangelidis
 */
public class help extends javax.swing.JFrame {

    /**
     * Creates new form help
     */
    public help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Για κινηθεί ένα κομμάτι πρέπει να πατηθεί το κουμπί, στο οποίο βρίσκεται \nκαι έπειτα το κουμπί του τετραγώνου μετακίνησης.\nΚάτω από το ταμπλό εμφανίζεται ανά πάσα στιγμή ποιου χρώματος γύρος είναι,\nεκτός αν ο χρήστης επιχειρήσει να κάνει κάποια μη αποδεκτή κίνηση.\nΣτην περίπτωση αυτή αναγράφεται ο λόγος, για τον οποίο δεν μπορεί να πραγματοποιηθεί η κίνηση.\nΙσχύουν οι κλασικοί κανόνες του παιχνιδιού (βλ. https://el.wikipedia.org/wiki/Κανόνες_του_σκακιού).\nΓια κάθε παίκτη υπάρχει ένα κουμπί παραίτησης στα δεξιά της σκακιέρας.\nΤο κουμπί είναι ενεργοποιημένο μόνο κατά τη διάρκεια του γύρου του παίκτη.\nΓια να παραιτηθεί ο χρήστης πρέπει να πατήσει το κουμπί παραίτησης δύο φορές.\nΑνάμεσα στα κουμπιά παραίτησης υπάρχει ένα κουμπί για συμφωνία ισοπαλίας.\nΓια να συμφωνηθεί ισοπαλία πρέπει και οι δύο παίκτες να το πατήσουνε συνεχόμενα.\nΑφού πατηθεί μία φορά απενεργοποιείται για αυτόν που το πάτησε \nκαι στο κουμπί αναγράφεται \"1/2\".Αν στον αμέσως επόμενο γύρο ο άλλος παίκτης πατήσει το κουμπί\nτότε το παιχνίδι θα τελειώσε με ισοπαλία.\nΥπάρχει κι ένα κουμπί για να αναιρεθεί η τελευταία κίνηση που έγινε, το κουμπί \"undo\".\nΠατώντας το, το παιχνίδι επιστρέφει στη θέση που ήταν πριν γίνει η τελευταία κίνηση και έπειτα\nτο κουμπί απενεργοποιείται μέχρι να ξαναγίνει κάποια κίνηση.\nΌταν πραγματοποιηθεί η πρώτη κίνηση στο παιχνίδι εμφανίζεται το παράθυρο ιστορικού κινήσεων.\nΣε αυτό αναγράφονται οι κινήσεις που γίνονται στο παιχνίδι. Στην κορυφή του παραθύρου \nαναγράφεται και το σκακιστικό άνοιγμα της συγκεκριμένης παρτίδας.");
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
