/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diepafiskaki;



public class Kinhseis extends javax.swing.JFrame {

    private String Text=" ";
   private boolean elegxosAnoigmatos=false;
    
    
    
    public Kinhseis() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kinhseis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ιστορικό κινήσεων");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        kinhseis.setColumns(20);
        kinhseis.setRows(5);
        jScrollPane2.setViewportView(kinhseis);
        kinhseis.setEditable(false);
        kinhseis.setLineWrap(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kinhseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kinhseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kinhseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kinhseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kinhseis().setVisible(true);
            }
        });
    }
    
    public void setText(String t,int c){
        
        Text = switch (c) {
            case 1 -> Text +  t;
            case 2 -> Text + "-" + t;
            default -> Text + "," + t;
        };
        
    
    kinhseis.setText(Text);
    
    if(!elegxosAnoigmatos)
    setLabel();
    
    
    }
    
    public void setText(String t){
    
    Text=t;
    
    kinhseis.setText(t);
    
    if(!elegxosAnoigmatos)
    setLabel();
    }
    
    
    public void setLabel()
    {
    
    if(Text.contains(" ε4")){jLabel1.setText("Άνοιγμα με το πιόνι του βασιλιά");
    
        switch (Text) {
            case " ε4-ε5,Ιζ3-Ιγ6,Αγ4" -> {
                jLabel1.setText("Ιταλική παρτίδα");
                elegxosAnoigmatos=true;
            }
            
            case " ε4-ε5,Ιζ3-Ιγ6,Αβ5" -> {jLabel1.setText("Ισπανική παρτίδα");
            elegxosAnoigmatos=true;}
            case " ε4-ε5,Ιζ3-Ιγ6,δ4" -> {jLabel1.setText("Σκωτσέζικη παρτίδα");
            elegxosAnoigmatos=true;}
        }
    
    }
    
    else if(Text.contains(" δ4")){jLabel1.setText("Άνοιγμα με το πιόνι της βασίλισσας");
    
    switch (Text) {
            case " δ4-δ5,Αζ4" -> {jLabel1.setText("Σύστημα Λονδίνου");
            elegxosAnoigmatos=true;}
            case " δ4-δ5,γ4" -> {jLabel1.setText("Γκαμπί βασίλισσας");
            elegxosAnoigmatos=true;}
            case " δ4-Ιζ6" -> {jLabel1.setText("Ινδική παρτίδα");
            elegxosAnoigmatos=true;}
            default -> {
            }
        }
    
    }
    
    else if(Text.contains(" γ4")){jLabel1.setText("Αγγλικό άνοιγμα");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" α4")){jLabel1.setText("Άνοιγμα του Ware");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" β4")){jLabel1.setText("Πολωνικό άνοιγμα");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" ζ4")){jLabel1.setText("Άνοιγμα του Bird");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" η4")){jLabel1.setText("Άνοιγμα του Grob");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" θ4")){jLabel1.setText("Άνοιγμα του Kadas");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" θ3")){jLabel1.setText("Άνοιγμα του Clemenz");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" α3")){jLabel1.setText("Άνοιγμα του Anderseen");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" β3")){jLabel1.setText("Επίθεση Nimzowitch-Larsen");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" γ3")){jLabel1.setText("Άνοιγμα Σαραγόσας");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" δ3")){jLabel1.setText("Άνοιγμα του Mieses");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" ε3")){jLabel1.setText("Άνοιγμα του Van't Kruijs");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" ζ3")){jLabel1.setText("Άνοιγμα του Barnes");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" η3")){jLabel1.setText("Φιανκέτο του βασιλιά");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" Iα3")){jLabel1.setText("Επίθεση νατρίου");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" Ιγ3")){jLabel1.setText("Άνοιγμα του Van Geet");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" Ιζ3")){jLabel1.setText("Άνοιγμα του Reti");
    elegxosAnoigmatos=true;}
    
    else if(Text.contains(" Ιθ3")){jLabel1.setText("Άνοιγμα του Amar");
    elegxosAnoigmatos=true;}
    
    
    }    
    public String getText(){return  Text;}
    
    public void resetLabel(){elegxosAnoigmatos=false;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea kinhseis;
    // End of variables declaration//GEN-END:variables
}
