
package diepafiskaki;

import java.awt.*;

import javax.swing.*;


public class Menou extends JFrame {

    private String[] epilogiXromatos;
    private String[] epipedoDyskolias;
    private String[] epilogiXronou;
    
    
    public Menou() {
        
        epilogiXromatos = new String[]{"Λευκά-Μαύρα","Λευκά-Πράσινα","Λευκά-Μπλε"};
        epipedoDyskolias = new String[]{"Εύκολο","Ενδιάμεσο","Δύσκολο"};
        epilogiXronou = new String[]{"0","3","5","10"};
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menou = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon image = new ImageIcon("a.jpg");
                g.drawImage(image.getImage(), 0, 0, this.getSize().width, this.getSize().height, null);
            }
        };
        menuLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        epiloges = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>(epilogiXromatos);
        bgrifoi = new javax.swing.JButton();
        Epipedo = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>(epipedoDyskolias);
        jComboBox3 = new javax.swing.JComboBox<>(epilogiXronou);
        labelXronou = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menou.setPreferredSize(new java.awt.Dimension(800, 500));

        menuLabel.setForeground(new java.awt.Color(51, 255, 51));
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("MENOY");
        menuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Νέο Παιχνίδι");
        jButton1.setToolTipText("Πατήστε εδώ για να ξεκινήσετε νέο παιχνίδι");
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Οδηγίες");
        jButton2.setToolTipText("Πατήστε εδώ για να διαβάσετε οδηγίες σχετικά με τη χρήση της εφαρμογής");
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setText("about");
        jButton3.setToolTipText("Πατήστε εδώ για να διαβάσετε πληροφορίες για τον δημιουργό της εφαρμογής");
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(true);
        jButton3.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        epiloges.setForeground(new java.awt.Color(51, 255, 51));
        epiloges.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        epiloges.setText("Επιλογή χρώματος σκακιέρας");

        jComboBox1.setToolTipText("Επιλέξτε το χρώμα της σκακιέρας");

        bgrifoi.setBackground(new java.awt.Color(255, 0, 51));
        bgrifoi.setText("Νέος Γρίφος");
        bgrifoi.setToolTipText("Πατήστε εδώ για να λύσετε έναν σκακιστικό γρίφο");
        bgrifoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgrifoiActionPerformed(evt);
            }
        });

        Epipedo.setForeground(new java.awt.Color(51, 255, 51));
        Epipedo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Epipedo.setText("Επιλογή επιπέδου γρίφου");

        jComboBox2.setToolTipText("Επιλέξτε το κατάλληλο επίπεδο δυσκολίας του γρίφου");

        jComboBox3.setToolTipText("Επιλέξτε πόσο χρόνο θα έχει ο κάθε παίκτης(0 σημαίνει χωρίς χρόνο)");

        labelXronou.setForeground(new java.awt.Color(51, 255, 51));
        labelXronou.setText("Επιλογή χρόνου ");

        javax.swing.GroupLayout menouLayout = new javax.swing.GroupLayout(menou);
        menou.setLayout(menouLayout);
        menouLayout.setHorizontalGroup(
            menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menouLayout.createSequentialGroup()
                .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menouLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bgrifoi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menouLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menouLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(epiloges, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menouLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(150, Short.MAX_VALUE))
                    .addGroup(menouLayout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(menouLayout.createSequentialGroup()
                        .addComponent(labelXronou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(71, 71, 71)
                        .addComponent(Epipedo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        menouLayout.setVerticalGroup(
            menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menouLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bgrifoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epiloges)
                    .addComponent(Epipedo)
                    .addComponent(labelXronou))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        menuLabel.setFont(new Font("Arial", Font.BOLD, 50));
        epiloges.setFont(new Font("Arial", Font.BOLD, 17));
        jComboBox1.getAccessibleContext().setAccessibleName("");
        bgrifoi.setBorderPainted(false);

        bgrifoi.setOpaque(true);
        Epipedo.setFont(new Font("Arial", Font.BOLD, 17));
        labelXronou.setFont(new Font("Arial", Font.BOLD, 17));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        
       this.setVisible(false);
         new DiepafiSkaki(jComboBox1.getSelectedItem().toString(),Integer.parseInt((String)jComboBox3.getSelectedItem()));
         
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Odigies().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new about().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bgrifoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgrifoiActionPerformed
             
       this.setVisible(false);
         new Grifoi(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_bgrifoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menou().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Epipedo;
    private javax.swing.JButton bgrifoi;
    private javax.swing.JLabel epiloges;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel labelXronou;
    private javax.swing.JPanel menou;
    private javax.swing.JLabel menuLabel;
    // End of variables declaration//GEN-END:variables
}
