/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diepafiskaki;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class Xronos extends javax.swing.JFrame {

    
    private static  int arxikosXronos ;
    private static final int afairesiXronou = 1;
    
     private int  xronosLeykou;
    private int   xronosMavrou;
    
    private boolean stopTime=false;
    
    private String gyros="White";
    
    private static String xroma;
  
    
    
    public Xronos(int ArxXr,String xrom) {
        
        arxikosXronos=ArxXr;
        xronosMavrou=arxikosXronos*60;
      xronosLeykou=arxikosXronos*60;
     
        
        xroma=xrom;
        
        initComponents();
        
         Timer timer = new Timer(afairesiXronou * 1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTimers();
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        XronosAsprou = new javax.swing.JLabel();
        XronosMavrou = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        XronosAsprou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XronosAsprou.setText("Χρόνος Λευκού");
        XronosAsprou.setToolTipText("ο χρόνος που απομένει στον παίκτη με τα λευκά");

        XronosMavrou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XronosMavrou.setText("Χρόνος Μαύρου");
        XronosMavrou.setToolTipText("ο χρόνος που απομένει για τον παίκτη με τα μαύρα");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(XronosMavrou, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XronosAsprou, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(XronosMavrou, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(XronosAsprou, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        XronosAsprou.getAccessibleContext().setAccessibleName("");
        XronosAsprou.setFont(new Font("Arial",Font.BOLD,25));
        XronosMavrou.setFont(new Font("Arial",Font.BOLD,25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Xronos(arxikosXronos,xroma).setVisible(true);
            }
        });
    }
    
    public void updateTimers() {
        // Update timers and check for game end
       
        if(!stopTime){
        if(gyros.equals("White")){
        xronosLeykou--;}
        
        else{
        xronosMavrou--;
        }}

        XronosAsprou.setText("Χρόνος Λευκού: " + formatTime(xronosLeykou));
        XronosMavrou.setText("Χρόνος Μαύρου: " + formatTime(xronosMavrou));
        
        if(xronosLeykou==0){endGame("White");}
        if(xronosMavrou==0){endGame("Black");}

        
    }

    public void endGame(String xrom) {
       
       if(xrom.equals("White")){
       new TelosPaixnidiou("Black",4,xroma,arxikosXronos).setVisible(true);}
       else{new TelosPaixnidiou("White",4,xroma,arxikosXronos).setVisible(true);}
       
       dispose();
        
    }

    public String formatTime(int seconds) {
        int minutes = seconds / 60;
        int remainingSeconds = seconds % 60;
        return String.format("%02d:%02d", minutes, remainingSeconds);
    }
    
    
public void StopTime(){

stopTime=true;

}

public void setGyros(String g){

gyros=g;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel XronosAsprou;
    private javax.swing.JLabel XronosMavrou;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
